"""
Django settings for myfundproject project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from decouple import config

load_dotenv()

# from channels_redis.core import RedisChannelLayer
# import redis

# Set your OpenAI API key

import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myfundproject.settings")


SSL_PORT = 8443  # You can choose any available port number

STATIC_ROOT = "/path/to/your/static/files/"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # <-- load your .env file


# now pull them in
IMAGEKIT_PRIVATE_KEY = os.getenv("IMAGEKIT_PRIVATE_KEY")
IMAGEKIT_PUBLIC_KEY = os.getenv("IMAGEKIT_PUBLIC_KEY")
IMAGEKIT_URL_ENDPOINT = os.getenv("IMAGEKIT_URL_ENDPOINT")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if os.environ.get("KOYEB_PUBLIC_DOMAIN") else True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "192.168.30.34",
    "10.0.101.10",
    "myfund.onrender.com",
    "localhost",
    "10.10.10.192",
    "192.168.10.60",
    "192.168.136.60",
    "192.168.170.60",
    "192.168.22.60",
    "192.168.235.60",
    "192.168.254.60",
    "192.168.90.60",
    "192.168.92.60",
    "192.168.71.60",
    "192.168.121.60",
    "192.168.212.60",
    "192.168.239.60",
    "192.168.92.60",
    "192.168.119.60",
    "192.168.204.60",
    "192.168.0.148",
    "172.20.10.2",
    "172.20.10.9",
    "10.10.10.27",
    "192.168.137.1",
    "10.0.0.140",
    "10.182.118.111",
    "192.168.1.148",
    "lipopectic-nonopinionatively-woodrow.ngrok-free.dev",
    "10.0.0.37",
    "10.5.8.33",
    "192.168.137.1",
    "172.24.144.1",
    "192.168.20.99",
    "192.168.20.159",
    '10.5.4.23',
    '192.168.20.47'
]

SECURE_SSL_REDIRECT = False  # Disable forced HTTPS redirect@
SESSION_COOKIE_SECURE = False  # Prevent forcing HTTPS for cookies
CSRF_COOKIE_SECURE = False  # Prevent CSRF issues with HTTPS


KOYEB_EXTERNAL_HOSTNAME = os.environ.get("KOYEB_PUBLIC_DOMAIN")
if KOYEB_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(KOYEB_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "authentication",
    "corsheaders",
    # "sslserver",
    "channels",
    "graphene_django",
    "django_extensions",
    "django_celery_beat",
]


ASGI_APPLICATION = "myfundproject.routing.application"
ADMIN_URL = "admin/"


# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER") == "True"
CELERY_TASK_IGNORE_RESULT = os.getenv("CELERY_TASK_IGNORE_RESULT") == "True"

# from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
#     'refund-contributions-task': {
#         'task': 'myfundproject.tasks.refund_contributions_if_goal_not_reached',
#         'schedule': crontab(minute=0, hour=0),  # Run daily at midnight
#     },
# }

REST_FRAMEWORK = {
    # Other settings...
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_TOKEN_EXPIRE_TIME": 60 * 60 * 24,  # Default is 1 day in seconds
}

# Increase the maximum number of fields allowed in a form submission
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000  # Default is 1000

# You might also want to increase these related settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB (default is 2.5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB (default is 2.5MB)

# Celery settings
# Celery settings
from celery.schedules import crontab

CELERY_BROKER_URL = os.environ.get("REDIS_URL")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Lagos"  # Keep your preferred timezone

# Additional Celery settings for better performance
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_CONCURRENCY = 2
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TRACK_STARTED = True


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=365 * 24 * 60 * 60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_LIFETIME": timedelta(days=7),
}

SESSION_COOKIE_AGE = 365 * 24 * 60 * 60  # 1 year


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    #   "channels.middleware.WebSocketMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins
CORS_ALLOWED_ORIGINS = [
    "https://tolulopeahmed.github.io",
    "https://10.10.4.82:8443",
    "https://www.myfundmobile.com",  # Add your domain here
    "http://192.168.238.34:8000",
    "https://myfund.onrender.com",
    "http://localhost:3000",
    "https://myfundapi-myfund-07ce351a.koyeb.app",
    "https://myfundmobile.com",
]

CORS_ALLOW_CREDENTIALS = True  # Allow credentials (useful for auth)
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-requested-with",
    "x-idempotency-key",
    "accept",
    "origin",
    "user-agent",
    "x-csrftoken",
]


if KOYEB_EXTERNAL_HOSTNAME:
    CORS_ALLOWED_ORIGINS.append(KOYEB_EXTERNAL_HOSTNAME)

# Excluding CSRF middleware for password reset endpoints
CSRF_EXCLUDE_URLS = [
    "/api/request-password-reset/",
    "/api/reset-password/",
]

ROOT_URLCONF = "myfundproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myfundproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")

if ENVIRONMENT == "production":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DATABASE_NAME"),
            "USER": os.getenv("DATABASE_USER"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD"),
            "HOST": os.getenv("DATABASE_HOST"),
            "PORT": os.getenv("DATABASE_PORT"),
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 20,  # Increase timeout value (in seconds)
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Following settings only make sense on production and may break development environments.
if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.CustomUser"


# PAYLESS SMS CONFIG
PAYLESS_SMS_URL = config("PAYLESS_SMS_URL")
PAYLESS_SMS_USERNAME = config("PAYLESS_SMS_USERNAME")
PAYLESS_SMS_PASSWORD = config("PAYLESS_SMS_PASSWORD")
PAYLESS_SMS_SENDER_ID = config("PAYLESS_SMS_SENDER_ID")

CELERY_TASK_ROUTES = {
    "authentication.tasks.send_namecheap_safe_email_task": {"queue": "emails"},
    "authentication.tasks.send_bulk_email_task": {"queue": "emails"},
    "authentication.tasks.calculate_daily_roi_task": {"queue": "critical"},
    "authentication.tasks.process_target_savings_deductions": {"queue": "critical"},
    "authentication.tasks.process_due_scheduled_withdrawals": {"queue": "critical"},
}

# ===== EMAIL CONFIGURATION =====
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = "MyFund <message@myfundmobile.com>"

# SSL (Implicit SSL)
EMAIL_HOST = "myfundmobile.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_TIMEOUT = 20

# # TLS (Explicit SSL)
# EMAIL_HOST = "myfundmobile.com"
# EMAIL_PORT = 587
# EMAIL_USE_SSL = False
# EMAIL_USE_TLS = True
# EMAIL_TIMEOUT = 20


EMAIL_HOST_USER = "info@myfundmobile.com"
EMAIL_HOST_PASSWORD = "Reproduction1..."


AUTHENTICATION_BACKENDS = [
    "authentication.auth_backends.CustomUserAdminAuthBackend",  # Custom admin authentication
    "authentication.auth_backends.CustomUserAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

#     os.environ['DJANGO_SECURE_SSL_REDIRECT'] = 'True'
#     os.environ['SSL_CERT_FILE'] = SSL_CERT  # Set the SSL certificate file
#     os.environ['SSL_KEY_FILE'] = SSL_KEY    # Set the SSL key file


# Configure Django to use HTTPS by default
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True


# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# settings.py
import os

if os.getenv("DJANGO_ENV") == "production":
    PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_KEY_LIVE")
else:
    PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_KEY_TEST")
