# Generated by Django 5.1.4 on 2025-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinvest',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autosave',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
