# Generated by Django 5.1.4 on 2025-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_topsaverhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_referral_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
