# Generated by Django 5.1.4 on 2025-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_last_referral_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_reward_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
