# Generated by Django 5.1.4 on 2025-07-26 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_referral_reward_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topsaverhistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='top_saver_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
