# Generated by Django 5.1.4 on 2025-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_customuser_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_otp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
