# Generated by Django 5.1.4 on 2025-08-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_autoinvest_paystack_plan_code_and_more'),
        ('authentication', '0012_customuser_last_otp_sent_at'),
    ]

    operations = [
    ]
