# Generated by Django 5.1.4 on 2025-08-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_fix_devicepushtoken_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsavings',
            name='deduction_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetsavings',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetsavings',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='targetsavings',
            name='frequency',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10),
        ),
        migrations.AddIndex(
            model_name='targetsavings',
            index=models.Index(fields=['is_active', 'next_deduction'], name='authenticat_is_acti_99e392_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsavings',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_4a647e_idx'),
        ),
    ]
