# Generated by Django 5.1.4 on 2025-08-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_targetsavings_deduction_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('CARD', 'Card'), ('WALLET', 'Wallet')], help_text='Where the transaction funds came from', max_length=20, null=True),
        ),
    ]
