# Generated by Django 5.1.4 on 2025-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsavings',
            name='next_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='targetsavings',
            index=models.Index(fields=['is_active', 'next_retry'], name='authenticat_is_acti_11092d_idx'),
        ),
    ]
