# Generated by Django 5.1.4 on 2025-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_targetsavings_next_retry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_reset_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
