# Generated by Django 5.1.4 on 2025-09-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_customuser_pin_reset_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSavingsCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_date', models.DateField()),
                ('was_on_time', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_savings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='authentication.targetsavings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_target_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
    ]
