# Generated by Django 5.1.4 on 2025-09-25 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_customuser_pin_reset_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
