# Generated by Django 5.1.4 on 2025-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_targetsavingscompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsavings',
            name='funding_source',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment')], default='SAVINGS', max_length=20),
        ),
    ]
