# Generated by Django 5.1.4 on 2025-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_targetsavings_funding_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsavingscompletion',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10),
        ),
    ]
