# Generated by Django 5.1.4 on 2025-09-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_targetsavingscompletion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsavings',
            name='max_attempts',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='targetsavingscompletion',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SUCCESS', max_length=10),
        ),
    ]
