# Generated by Django 5.1.4 on 2025-10-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_groupownership'),
        ('authentication', '0022_alter_targetsavings_max_attempts_and_more'),
    ]

    operations = [
    ]
