# Generated by Django 5.1.4 on 2025-10-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
