# Generated by Django 5.1.4 on 2025-10-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_customuser_pending_roi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROITransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('roi_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment')], max_length=10)),
                ('accrued_date', models.DateField()),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyROIAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('investment_balance', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('savings_roi', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('investment_roi', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total_roi', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_roi_accruals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
