# Generated by Django 5.1.4 on 2025-10-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_roitransaction_dailyroiaccrual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_top_saver_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Previous Top Savers ranking position', null=True),
        ),
    ]
