# Generated by Django 5.1.4 on 2025-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_customuser_last_top_saver_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='For scheduled withdrawals, the processing date.', null=True),
        ),
    ]
