# Generated by Django 5.1.4 on 2025-12-02 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDeparture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('financial', 'Financial constraints'), ('timeline', "Timeline doesn't work for me"), ('property', 'Changed mind about the property'), ('group', 'Issues with group members'), ('better_opportunity', 'Found a better investment opportunity'), ('personal', 'Personal reasons'), ('other', 'Other')], max_length=50)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('left_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='authentication.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-left_at'],
            },
        ),
    ]
