# Generated by Django 5.1.4 on 2025-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_groupdeparture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalsrequesttoadmin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Withdrawal Request', 'verbose_name_plural': 'Withdrawal Requests'},
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual charge amount deducted', max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage charge applied (e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original amount requested by user (including charges)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_access_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_auth_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Net amount to send to user (after charges)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='scheduled_processing_date',
            field=models.DateField(blank=True, help_text='Date when scheduled withdrawal should be processed', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='target_account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='target_bank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='withdrawal_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=50),
        ),
    ]
