# Generated by Django 5.1.4 on 2025-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_withdrawalsrequesttoadmin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Has scheduled withdrawal been credited to wallet?'),
        ),
    ]
