# Generated by Django 5.1.4 on 2025-12-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_withdrawalsrequesttoadmin_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_approval_status',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('submitted', 'Submitted (Pending Review)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
    ]
