# Generated by Django 5.1.4 on 2026-01-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_remove_customuser_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
