# Generated by Django 5.1.4 on 2026-01-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_transaction_idempotency_key"),
    ]

    operations = [
        # No-op migration.
        # The card fields were already removed in
        # 0035_alter_card_options_remove_card_card_number_and_more.
    ]