# Generated by Django 5.1.4 on 2026-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_card_options_remove_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='country_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
