# Generated by Django 5.1.4 on 2026-01-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_transaction_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pin',
        ),
    ]
