# Generated by Django 5.1.4 on 2026-01-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_card_account_name_card_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='account_name',
            new_name='card_owner_name',
        ),
    ]
