# Generated by Django 5.1.4 on 2026-03-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_remove_card_card_number_remove_card_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dva_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dva_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dva_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dva_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
