# Generated by Django 5.1.4 on 2026-02-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_transaction_idempotency_key'),
        ('authentication', '0037_rename_account_name_card_card_owner_name'),
    ]

    operations = [
    ]
