# Generated by Django 5.1.4 on 2026-02-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0038_merge_20260207_0049'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_deleted', 'date_joined'], name='authenticat_is_dele_c17343_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_deleted', 'savings', 'investment'], name='authenticat_is_dele_457207_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referral_id'], name='authenticat_referra_cdcbee_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_ambassador'], name='authenticat_is_amba_ee7464_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'status', 'transaction_type'], name='authenticat_date_084534_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date', 'status'], name='authenticat_user_id_22225f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source', 'transaction_type', 'status', 'date'], name='authenticat_source_9a1fb0_idx'),
        ),
    ]
