# Generated by Django 5.1.4 on 2026-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_customuser_dva_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paystack_identification_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paystack_identification_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paystack_identified',
            field=models.BooleanField(default=False),
        ),
    ]
