# Generated by Django 5.1.4 on 2026-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_dvadepositintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='target_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
