# Generated by Django 5.1.4 on 2026-03-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_alter_customuser_is_active_and_more'),
        ('authentication', '0041_withdrawalsrequesttoadmin_target_account_name'),
    ]

    operations = [
    ]
