# Generated by Django 5.1.4 on 2026-03-25 06:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0042_merge_20260325_0551"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorMonthlyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.CharField(db_index=True, max_length=7)),
                ("signups_submitted", models.PositiveIntegerField(default=0)),
                ("confirmed_submitted", models.PositiveIntegerField(default=0)),
                ("savings_submitted", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("attendance_submitted", models.PositiveIntegerField(default=0)),
                ("others_submitted", models.PositiveIntegerField(default=0)),
                ("coursera_submitted", models.PositiveIntegerField(default=0)),
                ("social_media_submitted", models.PositiveIntegerField(default=0)),
                ("abroad_confirmed_submitted", models.PositiveIntegerField(default=0)),
                ("events_submitted", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("coursera_certificate", models.ImageField(blank=True, null=True, upload_to="ambassador_reports/")),
                ("social_media_evidence", models.ImageField(blank=True, null=True, upload_to="ambassador_reports/")),
                ("abroad_signups_evidence", models.ImageField(blank=True, null=True, upload_to="ambassador_reports/")),
                ("events_evidence", models.ImageField(blank=True, null=True, upload_to="ambassador_reports/")),
                ("signups_approved", models.PositiveIntegerField(default=0)),
                ("confirmed_approved", models.PositiveIntegerField(default=0)),
                ("savings_approved", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("attendance_approved", models.PositiveIntegerField(default=0)),
                ("others_approved", models.PositiveIntegerField(default=0)),
                ("coursera_approved", models.PositiveIntegerField(default=0)),
                ("social_media_approved", models.PositiveIntegerField(default=0)),
                ("abroad_confirmed_approved", models.PositiveIntegerField(default=0)),
                ("events_approved", models.PositiveIntegerField(default=0)),
                ("signup_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("confirmed_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("savings_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("attendance_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("coursera_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("social_media_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("abroad_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("events_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("others_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("total_points_awarded", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("stipend_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("stipend_paid", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.CreateModel(
            name="AmbassadorPointConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Default Ambassador Config", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("signup_points", models.DecimalField(decimal_places=2, default=Decimal("0.50"), max_digits=6)),
                ("signup_points_cap", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=6)),
                ("confirmed_points", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=6)),
                ("savings_points_per_10000", models.DecimalField(decimal_places=2, default=Decimal("0.40"), max_digits=6)),
                ("savings_points_cap", models.DecimalField(decimal_places=2, default=Decimal("20.00"), max_digits=6)),
                ("attendance_points", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=6)),
                ("coursera_points", models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=6)),
                ("social_media_points", models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=6)),
                ("abroad_confirmed_points", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=6)),
                ("myfund_event_points", models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=6)),
                ("other_points", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ambassador Point Config",
                "verbose_name_plural": "Ambassador Point Config",
            },
        ),
        migrations.AddField(
            model_name="ambassadormonthlyreport",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_ambassador_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="ambassadormonthlyreport",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ambassador_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="ambassadormonthlyreport",
            unique_together={("user", "month")},
        ),
    ]