# Generated by Django 5.1.4 on 2026-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_ambassadormonthlyreport_ambassadorpointconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='authenticat_user_id_0c7591_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='authenticat_authori_5a6d2b_idx',
        ),
        migrations.RemoveField(
            model_name='card',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_first6_digits',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_last4_digits',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_owner_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_year',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reusable',
        ),
        migrations.RemoveField(
            model_name='card',
            name='signature',
        ),
        migrations.AlterField(
            model_name='card',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
