# Generated by Django 5.1.4 on 2026-03-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_alter_card_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorAttendanceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('takeaway', models.TextField()),
                ('recommendation', models.TextField()),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('week_key', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_attendance_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'week_key')},
            },
        ),
    ]
