# Generated by Django 5.1.4 on 2026-03-27 18:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_ambassadorattendancesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorattendancesubmission',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambassadorpointconfig',
            name='attendance_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6),
        ),
    ]
