# Generated by Django 5.1.4 on 2026-03-30 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_ambassadorattendancesubmission_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_first6_digits',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_last4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='country_code',
            field=models.CharField(blank=True, default='NG', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'is_active', 'is_default'], name='authenticat_user_id_8d34f1_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'is_active', 'reusable'], name='authenticat_user_id_14ff0a_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['authorization_code'], name='authenticat_authori_5a6d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['signature'], name='authenticat_signatu_552ce0_idx'),
        ),
    ]
