# Generated by Django 5.1.4 on 2026-03-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_alter_card_options_remove_customuser_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
    ]
