# Generated by Django 5.1.4 on 2026-04-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_alter_card_signature_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credited_to',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('WALLET', 'Wallet')], db_index=True, help_text='Where the transaction amount was credited to', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['credited_to', 'transaction_type', 'status', 'date'], name='authenticat_credite_a0da0e_idx'),
        ),
    ]
