# Generated by Django 5.1.4 on 2026-04-06 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_transaction_credited_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadormonthlyreport',
            name='reshares_approved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambassadormonthlyreport',
            name='reshares_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='ambassador_reports/'),
        ),
        migrations.AddField(
            model_name='ambassadormonthlyreport',
            name='reshares_points_awarded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='ambassadormonthlyreport',
            name='reshares_submitted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambassadorpointconfig',
            name='reshares_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=6),
        ),
    ]
