# Generated by Django 5.1.4 on 2026-04-09 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_ambassadormonthlyreport_reshares_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorpointconfig',
            name='coursera_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='ambassadorpointconfig',
            name='other_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='ambassadorpointconfig',
            name='reshares_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='ambassadorpointconfig',
            name='social_media_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='authorization_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_owner_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
