# Generated by Django 5.1.4 on 2026-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0054_drop_old_card_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User balance after this transaction', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User balance before this transaction', max_digits=14, null=True),
        ),
    ]
