# Generated by Django 5.1.4 on 2026-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0055_transaction_balance_after_transaction_balance_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('abrupt_withdrawal_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('float_gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roi_payable_to_users', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('float_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('property_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rent_commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_investment_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
    ]
