# Generated by Django 5.1.4 on 2026-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_financemetricsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvadepositintent',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
