# Generated by Django 5.1.4 on 2026-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_alter_dvadepositintent_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
