# Generated by Django 5.1.4 on 2026-05-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='For scheduled withdrawals - whether the scheduled withdrawal has been processed'),
        ),
    ]
