# Generated by Django 5.1.4 on 2026-05-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0060_transaction_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the withdrawal request', max_length=20, null=True),
        ),
    ]
