# Generated by Django 5.1.4 on 2026-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0061_withdrawalsrequesttoadmin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cac_proxy', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('float_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_float_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['period_type', 'snapshot_date'], name='authenticat_period__aaeafb_idx')],
            },
        ),
    ]
