# Generated by Django 5.1.4 on 2026-05-27 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_metricsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
