# Generated by Django 5.1.4 on 2026-05-31 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0064_customuser_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_phone', models.CharField(max_length=20)),
                ('new_phone', models.CharField(max_length=20)),
                ('changed_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
