# Generated by Django 5.1.4 on 2026-05-31 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_phonenumberchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_phone', models.CharField(max_length=20)),
                ('new_phone', models.CharField(max_length=20)),
                ('old_phone_otp_verified', models.BooleanField(default=False)),
                ('new_phone_otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('old_phone_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('new_phone_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
