# Generated by Django 5.1.4 on 2026-05-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_phonechangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberChangeLog',
        ),
    ]
