# Generated by Django 5.1.4 on 2026-07-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_delete_phonenumberchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=50)),
                ('reason', models.CharField(default='MyFund Allowance', max_length=100)),
                ('is_test', models.BooleanField(default=False)),
                ('test_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('credited', 'Credited'), ('test_run', 'Test Run'), ('user_not_found', 'User Not Found'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authentication.payrollrun')),
            ],
        ),
    ]
