# Generated by Django 5.1.4 on 2026-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_employee_payrollrun_payrollentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Draft)'), ('credited', 'Credited'), ('test_run', 'Test Run'), ('user_not_found', 'User Not Found'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
