# Generated by Django 5.1.4 on 2026-07-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_payrollentry_description_alter_payrollentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Engagement', 'Engagement'), ('CX', 'CX'), ('Operations', 'Operations'), ('Property', 'Property'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
