# Generated by Django 5.1.4 on 2026-08-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0071_groupincomeevent_groupincomedistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
