# Generated by Django 5.1.4 on 2026-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_group_completed_at_group_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('notify_transactions', models.BooleanField(default=True, help_text='QuickSave/QuickInvest initiation alerts')),
                ('notify_groupbuy', models.BooleanField(default=True, help_text='New GroupBuy live alerts')),
                ('notify_system', models.BooleanField(default=True, help_text='General admin/system broadcasts')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
