# Generated by Django 5.1.4 on 2026-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0073_adminnotifyrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotifyrecipient',
            name='notify_signups',
            field=models.BooleanField(default=True, help_text='New user signup alerts'),
        ),
    ]
