# Generated by Django 5.1.4 on 2026-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0074_adminnotifyrecipient_notify_signups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_required_version', models.CharField(default='1.0.0', help_text='Users on a version below this are force-blocked until they update.', max_length=20)),
                ('latest_version', models.CharField(default='1.0.0', help_text="Users on a version below this (but >= minimum) see a dismissible 'update available' prompt.", max_length=20)),
                ('play_store_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.tolulopeahmed.MyFundMobile')),
                ('app_store_url', models.URLField(default='https://apps.apple.com/ng/app/myfund-save-co-own-properties/id6747445574')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
