# Generated by Django 5.1.4 on 2026-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_appversionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsavings',
            name='schedule_anchor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
