# Generated by Django 5.1.4 on 2026-08-03 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_targetsavings_schedule_anchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsavings',
            name='category',
            field=models.CharField(choices=[('RENT_ACCOMMODATION', 'Rent & Accommodation'), ('EDUCATION', 'Education'), ('PHONE', 'Phone/Gadget'), ('CAR', 'Car'), ('BUSINESS', 'Business'), ('JAPA', 'Japa'), ('EMERGENCY', 'Emergency'), ('TRAVEL', 'Travel'), ('FEES_DEBT', 'Fees/Debt'), ('INVESTMENT', 'Investment'), ('GADGETS', 'Gadgets'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('WEDDING', 'Wedding'), ('FESTIVE', 'Festive Season (Sallah/Christmas/Eid)'), ('OTHERS', 'Others')], max_length=20, validators=[django.core.validators.RegexValidator(message='Category must be uppercase with underscores', regex='^[A-Z_]+$')]),
        ),
    ]
