# Generated by Django 5.0 on 2024-09-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('design_body', models.JSONField()),
                ('design_html', models.TextField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
