# Generated by Django 5.0 on 2024-09-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0077_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='design_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
