# Generated by Django 5.1.15 on 2026-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0078_add_email_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='extra_sent_today',
            field=models.IntegerField(default=0),
        ),
    ]
