# Generated by Django 5.1.15 on 2026-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0079_add_email_campaign_extra_sent_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='was_sent',
            field=models.BooleanField(default=False),
        ),
    ]
