# Generated by Django 5.0 on 2024-09-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0079_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='how_did_you_hear',
            field=models.CharField(choices=[('SM', 'Social Media - Facebook, Instagram, etc.'), ('IMs', 'Instant Messaging - WhatsApp, Telegram, etc.'), ('FF', 'Family and Friend'), ('GS', 'Google Search'), ('REC', 'Recommended'), ('CFG', 'Cashflow Game'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
