# Generated by Django 5.1.15 on 2026-08-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_add_email_template_was_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
