# Generated by Django 5.0 on 2024-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_alter_customuser_how_did_you_hear'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
