# Generated by Django 5.1.15 on 2026-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_add_email_template_recipient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
    ]
