# Generated by Django 5.0 on 2024-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hired_referrer',
            field=models.BooleanField(default=False),
        ),
    ]
