# Generated by Django 5.0 on 2024-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0083_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinvest',
            name='paystack_sub_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autoinvest',
            name='paystack_sub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autoinvest',
            name='paystack_sub_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autosave',
            name='paystack_sub_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autosave',
            name='paystack_sub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autosave',
            name='paystack_sub_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
