# Generated by Django 5.1.15 on 2026-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0084_cleanup_orphaned_target_savings_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupownership',
            name='properties_credited',
            field=models.BooleanField(default=False),
        ),
    ]
