# Generated by Django 5.0 on 2024-10-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0084_autoinvest_paystack_sub_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosave',
            name='card',
        ),
        migrations.RemoveField(
            model_name='autosave',
            name='user',
        ),
        migrations.DeleteModel(
            name='AutoInvest',
        ),
        migrations.DeleteModel(
            name='AutoSave',
        ),
    ]
