# Generated by Django 5.1.15 on 2026-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0085_add_properties_credited_to_groupownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupownership',
            name='listed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupownership',
            name='listed_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
