# Generated by Django 5.0 on 2024-11-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_autoinvest_paystack_sub_code_and_more'),
        ('authentication', '0086_autoinvest_autosave'),
    ]

    operations = [
    ]
