# Generated by Django 5.0 on 2024-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_merge_20241109_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosave',
            name='paystack_trans_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
