# Generated by Django 5.1.15 on 2026-09-01 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_rename_is_hired_referrer_to_is_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemetricsnapshot',
            name='ambassador_stipend_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='financemetricsnapshot',
            name='operating_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='financemetricsnapshot',
            name='payroll_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('software', 'Software & Tools'), ('infrastructure', 'Infrastructure & Hosting'), ('marketing', 'Marketing'), ('legal', 'Legal & Compliance'), ('office', 'Office & Admin'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_incurred', models.DateField(help_text='Which day/month this expense counts toward in the P&L.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_operating_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_incurred', '-created_at'],
            },
        ),
    ]
