# Generated by Django 5.1.15 on 2026-09-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0088_financemetricsnapshot_ambassador_stipend_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CxWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(help_text='What happened this week')),
                ('recommendation', models.TextField(blank=True, default='', help_text='Suggested improvement to the report/UX/process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cx_weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
