# Generated by Django 5.0 on 2024-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0088_autosave_paystack_trans_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinvest',
            name='paystack_trans_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
