# Generated by Django 5.1.15 on 2026-09-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0089_add_cxweeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxweeklyreport',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
