# Generated by Django 5.1.15 on 2026-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0090_cxweeklyreport_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_undeliverable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
