# Generated by Django 5.0 on 2024-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0090_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='paystack_transaction_reference',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
