# Generated by Django 5.1.15 on 2026-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0091_customuser_email_undeliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
