# Generated by Django 5.1.15 on 2026-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0092_customuser_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_campaign_email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='audience',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='segment_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='send_mode',
            field=models.CharField(blank=True, choices=[('broadcast', 'Broadcast'), ('personalised', 'Personalised')], default='', max_length=20),
        ),
    ]
