# Generated by Django 5.0 on 2024-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0092_rename_withdrawalrequest_pendingwithdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingwithdrawals',
            name='transaction_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
