# Generated by Django 5.1.15 on 2026-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0093_customuser_last_campaign_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='template_mode',
            field=models.CharField(choices=[('branded', 'Branded'), ('plain', 'Plain')], default='branded', max_length=20),
        ),
    ]
