# Generated by Django 5.1.15 on 2026-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0095_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('user', 'account_number', 'bank_code'), name='unique_bank_account_per_user_and_bank'),
        ),
    ]
