# Generated by Django 5.1.4 on 2025-01-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0096_migrate_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
