# Generated by Django 5.0 on 2025-01-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0094_customuser_country_customuser_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingWithdrawals',
            new_name='WithdrawalsRequestToAdmin',
        ),
    ]
