# Generated by Django 5.1.4 on 2025-02-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_autoinvest_paystack_sub_code_and_more'),
        ('authentication', '0097_remove_customuser_password'),
    ]

    operations = [
    ]
