# Generated by Django 5.1.4 on 2025-01-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0095_rename_pendingwithdrawals_withdrawalsrequesttoadmin'),
        ('authentication', '0097_remove_customuser_password'),
    ]

    operations = [
    ]
