# Generated by Django 5.1.15 on 2026-09-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0098_emailcampaign_sender_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ambassador Cohort',
                'verbose_name_plural': 'Ambassador Cohorts',
                'ordering': ['cohort_number'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='ambassador_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='authentication.ambassadorcohort'),
        ),
    ]
