# Generated by Django 5.1.4 on 2025-02-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0098_merge_20250205_0458'),
        ('authentication', '0099_merge_20250125_0427'),
    ]

    operations = [
    ]
