# Generated by Django 5.1.15 on 2026-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0100_backfill_ambassador_cohorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorcohort',
            name='send_forth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
