# Generated by Django 5.1.15 on 2026-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0101_ambassadorcohort_send_forth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_upload',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
