# Generated by Django 5.1.4 on 2025-02-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0101_contribution_group_contribution_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
