# Generated by Django 5.1.4 on 2025-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0102_alter_group_total_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='minimum_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
