# Generated by Django 5.1.4 on 2025-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0103_group_minimum_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='group',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
