# Generated by Django 5.1.4 on 2025-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0104_alter_contribution_amount_alter_group_goal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rent_earned_annually',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rent_earned_monthly',
        ),
    ]
