# Generated by Django 5.1.15 on 2026-09-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0104_phonechangerequest_otp_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ambassador_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ambassador Certificate',
                'verbose_name_plural': 'Ambassador Certificates',
            },
        ),
    ]
