# Generated by Django 5.1.4 on 2025-02-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0100_merge_20250206_1456'),
        ('authentication', '0105_remove_transaction_property_name_and_more'),
    ]

    operations = [
    ]
