# Generated by Django 5.1.15 on 2026-09-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0105_ambassadorcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorcertificate',
            name='early_access',
            field=models.BooleanField(default=False, help_text='Allow this certificate holder access before their cohort release date.'),
        ),
        migrations.CreateModel(
            name='InfluencerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_content', models.PositiveIntegerField()),
                ('monthly_signups', models.PositiveIntegerField()),
                ('monthly_savers', models.PositiveIntegerField()),
                ('social_links', models.TextField()),
                ('plan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
