# Generated by Django 5.1.15 on 2026-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0106_ambassadorcertificate_early_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerapplication',
            name='follow_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
