# Generated by Django 5.1.4 on 2025-02-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0106_merge_20250220_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='source',
            field=models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('wallet', 'Wallet')], default='wallet', max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=7),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
