# Generated by Django 5.1.15 on 2026-09-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0107_influencerapplication_follow_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerapplication',
            name='commitment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='contact_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='engagement_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='niche',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='portfolio_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='social_followers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='why_influencer',
            field=models.TextField(default=''),
        ),
    ]
