# Generated by Django 5.1.4 on 2025-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0107_contribution_source_alter_contribution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='source',
            field=models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('wallet', 'Wallet')], default='', max_length=10),
        ),
    ]
