# Generated by Django 5.1.15 on 2026-09-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0108_influencerapplication_commitment_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerapplication',
            name='social_followers',
        ),
        migrations.AddField(
            model_name='influencerapplication',
            name='total_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
