# Generated by Django 5.1.4 on 2025-02-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0108_alter_contribution_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='source',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Investment', 'Investment'), ('Wallet', 'Wallet')], default='', max_length=10),
        ),
    ]
