# Generated by Django 5.1.4 on 2025-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0109_alter_contribution_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='ownership_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
