# Generated by Django 5.1.15 on 2026-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0109_remove_influencerapplication_social_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushcampaign',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
