# Generated by Django 5.1.4 on 2025-02-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0110_contribution_ownership_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='source',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Investment', 'Investment'), ('Wallet', 'Wallet')], max_length=10),
        ),
    ]
