# Generated by Django 5.1.15 on 2026-10-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0110_pushcampaign_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxweeklyreport',
            name='department',
            field=models.CharField(choices=[('CX', 'CX'), ('Engagement', 'Engagement')], db_index=True, default='CX', max_length=20),
        ),
    ]
