# Generated by Django 5.1.15 on 2026-10-04 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0111_weekly_report_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorEmailChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('reminder_consent', models.BooleanField(default=False)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ambassadorintake')),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Not selected')], db_index=True, default='draft', max_length=20)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('reminder_consent', models.BooleanField(default=False)),
                ('video_file_id', models.CharField(blank=True, max_length=200)),
                ('video_path', models.CharField(blank=True, max_length=1000)),
                ('video_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('review_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.ambassadorintake')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('intake', 'email'), name='unique_ambassador_intake_email')],
            },
        ),
    ]
