# Generated by Django 5.1.4 on 2025-03-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0112_savingsgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='auto_debit',
            new_name='auto_debit_enabled',
        ),
    ]
