# Generated by Django 5.1.4 on 2025-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0113_rename_auto_debit_savingsgoal_auto_debit_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ambassador',
            field=models.BooleanField(default=False),
        ),
    ]
