# Generated by Django 5.1.15 on 2026-10-07 17:44

import authentication.foya_models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed(apps, schema_editor):
    from datetime import datetime
    from zoneinfo import ZoneInfo
    from django.utils import timezone
    wat = ZoneInfo("Africa/Lagos")
    Campaign = apps.get_model("authentication", "FoyaCampaign")
    Push = apps.get_model("authentication", "FoyaPush")
    if Campaign.objects.exists():
        return
    campaign = Campaign.objects.create(
        is_active=True,
        start_at=timezone.now(),
        end_at=datetime(2026, 11, 4, 21, 59, tzinfo=wat),  # 23:59 EAT
        categories=[
            {"key": "founder", "label": "Founder of the Year", "url": "https://foyaglobal.com/nigeria/founder-of-the-year/over_30/DZSWHYIB"},
            {"key": "realestate", "label": "Real Estate & Urban Development", "url": "https://foyaglobal.com/nigeria/real-estate-urban-development/over_30/2MK5XN56"},
            {"key": "fintech", "label": "Fintech & Financial Innovation", "url": "https://foyaglobal.com/nigeria/fintech-financial-innovation/over_30/KHAKYQLB"},
        ],
        # Mon founder, Tue realestate, Wed founder, Thu fintech, Fri founder, Sat realestate, Sun founder
        weekday_schedule={"0": "founder", "1": "realestate", "2": "founder", "3": "fintech", "4": "founder", "5": "realestate", "6": "founder"},
    )
    Push.objects.bulk_create([
        # Launch is timed by hand in the admin once the banner is live.
        Push(campaign=campaign, slot="launch", send_at=None,
             title="MyFund is nominated at the FOYA Global Honors 2026",
             body="Vote for us free, once a day, until 4 November. Tap to see how."),
        Push(campaign=campaign, slot="final_week", send_at=datetime(2026, 10, 28, 10, 0, tzinfo=wat),
             title="One week left to back MyFund",
             body="Your free daily vote still counts. Tap to vote today."),
        Push(campaign=campaign, slot="last_day", send_at=datetime(2026, 11, 4, 10, 0, tzinfo=wat),
             title="FOYA voting closes tonight",
             body="Cast your free vote for MyFund before 9:59pm today. Tap to vote."),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0114_intake_programme_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoyaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=authentication.foya_models.default_end_at)),
                ('signup_url', models.URLField(default='https://foyaglobal.com/signup')),
                ('login_url', models.URLField(default='https://foyaglobal.com/login')),
                ('categories', models.JSONField(default=list)),
                ('weekday_schedule', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'FOYA campaign',
            },
        ),
        migrations.CreateModel(
            name='FoyaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('banner_view', 'banner_view'), ('banner_tap', 'banner_tap'), ('push_open', 'push_open'), ('signup_tap', 'signup_tap'), ('login_tap', 'login_tap'), ('vote_tap', 'vote_tap'), ('dismiss', 'dismiss')], db_index=True, max_length=20)),
                ('category_key', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(choices=[('banner', 'Banner'), ('push', 'Push')], default='banner', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOYA event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoyaPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('launch', 'Launch'), ('final_week', 'Final week'), ('last_day', 'Last day')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=240)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to='authentication.foyacampaign')),
            ],
            options={
                'verbose_name': 'FOYA push',
                'ordering': ['send_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'slot'), name='unique_foya_push_slot')],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
