# Generated by Django 5.1.4 on 2025-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0114_customuser_is_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='source_account',
            field=models.CharField(default='savings', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='target_account_number',
            field=models.CharField(default='8033924595', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='target_bank',
            field=models.CharField(default='Palmpay', max_length=100),
        ),
    ]
