# Generated by Django 5.1.15 on 2026-10-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def new_schedule(apps, schema_editor):
    # Mon-Fri Founder of the Year, Sat Real Estate, Sun Fintech.
    Campaign = apps.get_model("authentication", "FoyaCampaign")
    Campaign.objects.update(weekday_schedule={
        "0": "founder", "1": "founder", "2": "founder", "3": "founder", "4": "founder",
        "5": "realestate", "6": "fintech",
    })


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0115_foya_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyacampaign',
            name='show_position',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FoyaPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(db_index=True, max_length=40)),
                ('position', models.PositiveIntegerField()),
                ('field_size', models.PositiveIntegerField()),
                ('is_tied', models.BooleanField(default=False)),
                ('previous_position', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_field_size', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_is_tied', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='authentication.foyacampaign')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOYA position',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.RunPython(new_schedule, migrations.RunPython.noop),
    ]
