# Generated by Django 5.1.4 on 2025-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0115_withdrawalsrequesttoadmin_source_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='target_account_number',
            field=models.CharField(default='8033924595', max_length=50),
        ),
    ]
