# Generated by Django 5.1.4 on 2025-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0116_alter_withdrawalsrequesttoadmin_target_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalsrequesttoadmin',
            name='transaction_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
