# Generated by Django 5.1.15 on 2026-10-08 07:29

import django.db.models.deletion
from django.db import migrations, models


def enable_daily_push(apps, schema_editor):
    # Queued: one push a day at 10:00 WAT from 9 Oct 2026.
    from datetime import date
    Campaign = apps.get_model("authentication", "FoyaCampaign")
    Campaign.objects.update(daily_push_enabled=True, daily_push_start=date(2026, 10, 9), daily_push_hour=10)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0117_foya_banner_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyacampaign',
            name='daily_push_body',
            field=models.CharField(default="It's free, once a day. {days_left}. Tap to vote.", max_length=240),
        ),
        migrations.AddField(
            model_name='foyacampaign',
            name='daily_push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foyacampaign',
            name='daily_push_hour',
            field=models.PositiveSmallIntegerField(default=10, help_text='Hour of day in WAT (8-20).'),
        ),
        migrations.AddField(
            model_name='foyacampaign',
            name='daily_push_start',
            field=models.DateField(blank=True, help_text='First day (WAT) the daily push goes out.', null=True),
        ),
        migrations.AddField(
            model_name='foyacampaign',
            name='daily_push_title',
            field=models.CharField(default='Vote MyFund for {label} today', max_length=120),
        ),
        migrations.CreateModel(
            name='FoyaDailyPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category_key', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.CharField(blank=True, max_length=240)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_pushes', to='authentication.foyacampaign')),
            ],
            options={
                'verbose_name': 'FOYA daily push',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'date'), name='unique_foya_daily_push_date')],
            },
        ),
        migrations.RunPython(enable_daily_push, migrations.RunPython.noop),
    ]
