# Generated by Django 5.1.15 on 2026-10-08 07:45

from django.db import migrations, models


def new_copy(apps, schema_editor):
    Campaign = apps.get_model("authentication", "FoyaCampaign")
    Campaign.objects.update(
        daily_push_title="Vote for MyFund (FOYA)",
        daily_push_body="MyFund has been nominated for the FOYA Global Awards 2026. {standing} {days_left}. Tap to vote for today.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0118_foya_daily_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foyacampaign',
            name='daily_push_body',
            field=models.CharField(default='MyFund has been nominated for the FOYA Global Awards 2026. {standing} {days_left}. Tap to vote for today.', help_text='Placeholders: {standing} ("Now 2nd of 9 for <category>." or "Vote for <category>."), {label}, {position}, {field}, {days_left}.', max_length=240),
        ),
        migrations.AlterField(
            model_name='foyacampaign',
            name='daily_push_title',
            field=models.CharField(default='Vote for MyFund (FOYA)', max_length=120),
        ),
        migrations.RunPython(new_copy, migrations.RunPython.noop),
    ]
