# Generated by Django 5.1.4 on 2025-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0119_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferrequest',
            name='transaction_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
