# Generated by Django 5.1.4 on 2025-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0120_alter_banktransferrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_reward_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
