# Generated by Django 5.1.4 on 2025-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0121_customuser_referral_reward_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinvest',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
