# Generated by Django 5.1.4 on 2025-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0124_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, default=12345, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
