# Generated by Django 5.1.4 on 2025-04-21 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0125_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('RENT', 'Rent/Accommodation'), ('EDUCATION', 'Education'), ('PHONE', 'Phone/Gadget'), ('CAR', 'Car'), ('BUSINESS', 'Business'), ('JAPA', 'Japa'), ('EMERGENCY', 'Emergencies'), ('TRAVEL', 'Travel'), ('FEES_DEBT', 'Fees or Debt'), ('INVESTMENT', 'Investment'), ('GADGETS', 'Gadgets'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('OTHERS', 'Others')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_source', models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('CARD', 'Card')], default='SAVINGS', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('next_deduction', models.DateTimeField(blank=True, null=True)),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_savings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.targetsavings'),
        ),
    ]
