# Generated by Django 5.1.4 on 2025-04-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0126_targetsavings_transaction_target_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsavings',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('EDUCATION', 'Education'), ('PHONE', 'Phone/Gadget'), ('CAR', 'Car'), ('BUSINESS', 'Business'), ('JAPA', 'Japa'), ('EMERGENCY', 'Emergency'), ('TRAVEL', 'Travel'), ('FEES_DEBT', 'Fees/Debt'), ('INVESTMENT', 'Investment'), ('GADGETS', 'Gadgets'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('OTHERS', 'Others')], default='OTHER', max_length=20),
        ),
    ]
