# Generated by Django 5.1.4 on 2025-04-21 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0128_alter_targetsavings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
