# Generated by Django 5.1.4 on 2025-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0129_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='referral',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
