# Generated by Django 5.1.4 on 2025-05-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0130_alter_referral_options_referral_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={},
        ),
        migrations.RemoveField(
            model_name='referral',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='referral',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='authentication.transaction'),
        ),
    ]
