# Generated by Django 5.1.4 on 2025-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0133_transaction_referral_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(db_index=True, default='No description available', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='referral_email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
