# Generated by Django 5.1.4 on 2025-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0135_monthlyfinancialrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_access_code',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
