# Generated by Django 5.1.4 on 2025-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0135_monthlyfinancialrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalsrequesttoadmin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='scheduled_processing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalsrequesttoadmin',
            name='withdrawal_type',
            field=models.CharField(default='immediate', max_length=50),
        ),
    ]
