# Generated by Django 5.1.4 on 2025-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0136_alter_withdrawalsrequesttoadmin_options_and_more'),
        ('authentication', '0136_transaction_paystack_access_code'),
    ]

    operations = [
    ]
