# Generated by Django 5.1.4 on 2025-07-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0137_merge_20250702_0426'),
        ('authentication', '0138_customuser_expo_push_token_and_more'),
    ]

    operations = [
    ]
