# Generated by Django 5.1.4 on 2025-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0138_customuser_expo_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_auth_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
