# Generated by Django 5.1.4 on 2025-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0139_merge_20250705_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_auth_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_access_code',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
