# Generated by Django 5.1.4 on 2025-07-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0139_transaction_paystack_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paystack_access_code',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_auth_code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
    ]
