# Generated by Django 5.1.4 on 2025-07-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0141_alter_transaction_paystack_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expo_push_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expo_push_tokens',
            field=models.JSONField(default=list),
        ),
    ]
