# Generated by Django 5.1.4 on 2025-07-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0142_remove_customuser_expo_push_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expo_push_tokens',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
