# Generated by Django 5.1.4 on 2025-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0143_remove_customuser_expo_push_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
