# Generated by Django 5.1.4 on 2025-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0144_customuser_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expo_push_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expo_push_tokens',
            field=models.JSONField(default=list),
        ),
    ]
