# Generated by Django 5.1.4 on 2025-07-06 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0145_remove_customuser_device_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Push Notification', 'verbose_name_plural': 'Push Notifications'},
        ),
        migrations.AddField(
            model_name='pushnotifications',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
