# Generated by Django 5.1.4 on 2025-07-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0146_alter_pushnotifications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pushnotifications',
            name='users',
        ),
    ]
